-- Rollback: Remove source tracking from JournalEntry table
-- Purpose: Revert changes from 001_add_journal_entry_source.sql
-- Author: Phase 1 Task 1.1
-- Date: 2025-11-08

BEGIN;

-- Drop indexes
DROP INDEX IF EXISTS "idx_journal_entry_auto_generated";
DROP INDEX IF EXISTS "idx_journal_entry_source";

-- Drop constraint
ALTER TABLE "JournalEntry"
DROP CONSTRAINT IF EXISTS "journal_entry_source_type_check";

-- Restore sourceId to VARCHAR(100) if it was changed from VARCHAR to TEXT
-- (This handles the case where sourceId existed before the migration)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'JournalEntry' 
    AND column_name = 'sourceId' 
    AND data_type = 'text'
  ) THEN
    -- Check if there's a sourceModule column (indicates pre-existing schema)
    -- If sourceModule exists, sourceId was likely VARCHAR(100) originally
    IF EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_schema = 'public' 
      AND table_name = 'JournalEntry' 
      AND column_name = 'sourceModule'
    ) THEN
      ALTER TABLE "JournalEntry" ALTER COLUMN "sourceId" TYPE varchar(100);
    END IF;
  END IF;
END $$;

-- Drop only the columns that were added by this migration
ALTER TABLE "JournalEntry"
DROP COLUMN IF EXISTS "autoGenerated",
DROP COLUMN IF EXISTS "sourceType";

-- Note: We do NOT drop sourceId here because it may have existed before this migration
-- If sourceId was added by this migration, it will remain as TEXT
-- If sourceId existed before, it will be restored to VARCHAR(100) by the DO block above

COMMIT;
