-- Migration: Add source tracking to JournalEntry table
-- Purpose: Link journal entries to their originating transactions
-- Author: Phase 1 Task 1.1
-- Date: 2025-11-08

BEGIN;

-- Add source tracking columns (idempotent - only add if they don't exist)
DO $$
BEGIN
  -- Add sourceType column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'JournalEntry' 
    AND column_name = 'sourceType'
  ) THEN
    ALTER TABLE "JournalEntry" ADD COLUMN "sourceType" varchar(50);
  END IF;

  -- Handle sourceId column (may already exist as VARCHAR(100))
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'JournalEntry' 
    AND column_name = 'sourceId'
  ) THEN
    ALTER TABLE "JournalEntry" ADD COLUMN "sourceId" text;
  ELSE
    -- If sourceId exists as VARCHAR(100), alter it to TEXT for consistency
    IF EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_schema = 'public' 
      AND table_name = 'JournalEntry' 
      AND column_name = 'sourceId' 
      AND data_type = 'character varying'
    ) THEN
      ALTER TABLE "JournalEntry" ALTER COLUMN "sourceId" TYPE text;
    END IF;
  END IF;

  -- Add autoGenerated column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'JournalEntry' 
    AND column_name = 'autoGenerated'
  ) THEN
    ALTER TABLE "JournalEntry" ADD COLUMN "autoGenerated" boolean DEFAULT false NOT NULL;
  END IF;
END $$;

-- Add CHECK constraint for valid source types (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE table_schema = 'public' 
    AND constraint_name = 'journal_entry_source_type_check'
  ) THEN
    ALTER TABLE "JournalEntry"
    ADD CONSTRAINT "journal_entry_source_type_check"
    CHECK ("sourceType" IS NULL OR "sourceType" IN (
      'INVOICE',
      'JOB_COMPLETION',
      'PURCHASE_ORDER',
      'TIME_APPROVAL',
      'MANUAL_ADJUSTMENT',
      'VENDOR_INVOICE',
      'PAYROLL_ACCRUAL'
    ));
  END IF;
END $$;

-- Create index for efficient source lookups (idempotent)
CREATE INDEX IF NOT EXISTS "idx_journal_entry_source"
ON "JournalEntry" ("sourceType", "sourceId")
WHERE "sourceType" IS NOT NULL;

-- Create index for auto-generated entries (idempotent)
CREATE INDEX IF NOT EXISTS "idx_journal_entry_auto_generated"
ON "JournalEntry" ("autoGenerated")
WHERE "autoGenerated" = true;

-- Add comments for documentation
COMMENT ON COLUMN "JournalEntry"."sourceType" IS 'Type of transaction that generated this journal entry (INVOICE, JOB_COMPLETION, etc.)';
COMMENT ON COLUMN "JournalEntry"."sourceId" IS 'ID of the source transaction (e.g., invoice ID, job ID)';
COMMENT ON COLUMN "JournalEntry"."autoGenerated" IS 'True if this entry was created automatically by the system';

COMMIT;
