-- Add PENDING_APPROVAL to JobStatus enum
ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';

-- Add comment explaining the status
COMMENT ON TYPE "JobStatus" IS 'Job status enum: ESTIMATE, SCHEDULED, DISPATCHED, IN_PROGRESS, COMPLETED, BILLED, CANCELLED, PENDING_APPROVAL';
